---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- example.yaml
configurations:
- .transformers.yaml
namePrefix: "cnbi-bot-"
commonLabels:
  app.kubernetes.io/component: task
images:
- name: example
  newName: quay.io/operate-first/opf-toolbox:v0.5.0
